# fly.toml app configuration file generated for brocelianzoo on 2024-05-18T17:50:27+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'brocelianzoo'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = "connections"
    hard_limit = 999
    soft_limit = 999

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
